name: personal website CI/CD
on:
  workflow_dispatch:
      
  push:
    branches:
      - master
    paths:
      - 'src*'

env:
  AWS_REGION: "ap-northeast-1"
  AWS_ROLE_ARN: ${{ (github.ref == endsWith(github.ref, '/main') && secrets.AWS_PRODUCT_ROLE_ARN) || secrets.AWS_STAGING_ROLE_ARN }}

# AWS OpenID Connect用
permissions:
  id-token: write
  contents: read

jobs:
  test-and-deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: src/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: src
      - name: export html
        if: github.ref == endsWith(github.ref, '/main')
        run: npm run build
        working-directory: src
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region:  ${{ env.AWS_REGION }}
      - run: aws sts get-caller-identity
      - name: set env(product)
        if: github.ref == endsWith(github.ref, '/main')
        run: echo 'ENVIRONMENT=product' >> $GITHUB_ENV
      - name: set env(staging)
        if: contains(github.ref, '/feature')
        run: echo 'ENVIRONMENT=staging' >> $GITHUB_ENV
      - name: deploy to s3
        run: bash ./src/upload.sh $ENVIRONMENT
      - name: Slack notification of success
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_COLOR: good 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Deploy success.'
          SLACK_TITLE: GitHub Actions Notification
      - name: Slack notification of failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Deploy failed...'
          SLACK_TITLE: GitHub Actions Notification
